# Generated by Django 5.2.17 on 2026-09-19 04:32

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SUBMIT', 'Ready to submit'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REVISION_REQUIRED', 'Revision required'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('rooms_snapshot', models.PositiveIntegerField()),
                ('max_guests_snapshot', models.PositiveIntegerField()),
                ('restaurant_snapshot', models.BooleanField()),
                ('classification_outcome_snapshot', models.CharField(choices=[('NOT_HOTEL', 'Not a hotel'), ('TYPE_1', 'Type 1'), ('TYPE_2', 'Type 2'), ('OUT_OF_SCOPE', 'Out of scope'), ('REQUIRES_LICENSE_REVIEW', 'Requires license review')], max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('priority', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('min_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('min_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('max_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('restaurant_value', models.BooleanField(blank=True, null=True)),
                ('outcome_code', models.CharField(choices=[('NOT_HOTEL', 'Not a hotel'), ('TYPE_1', 'Type 1'), ('TYPE_2', 'Type 2'), ('OUT_OF_SCOPE', 'Out of scope'), ('REQUIRES_LICENSE_REVIEW', 'Requires license review')], max_length=50)),
                ('guidance_key', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('OPERATOR_PREPARED', 'Operator prepared'), ('EXTERNAL_AGENCY', 'External agency')], max_length=30)),
                ('approximate_processing_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('validity_years', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['property_type', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='IssuingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'issuing agencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LocalAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('official_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'local authorities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('APPLICANT', 'Applicant'), ('LOCAL_OFFICER', 'Local officer'), ('CENTRAL_OFFICER', 'Central officer'), ('SUPER_ADMIN', 'Super admin')], default='APPLICANT', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('local_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='core.localauthority')),
            ],
            managers=[
                ('objects', apps.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('APPROVED', 'Approved'), ('REVISION_REQUIRED', 'Revision required'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='core.documenttype')),
            ],
            options={
                'ordering': ['document_type_id', '-version'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='classification_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.classificationrule'),
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('APPROVED', 'Approved'), ('REVISION_REQUIRED', 'Revision required'), ('REJECTED', 'Rejected')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('application_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.applicationdocument')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reviewed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('supporting_items', models.TextField(blank=True, help_text='One display item per line.')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.documenttype')),
            ],
        ),
        migrations.AddField(
            model_name='documenttype',
            name='issuing_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_types', to='core.issuingagency'),
        ),
        migrations.CreateModel(
            name='IssuingAgencyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_notes', models.TextField(blank=True)),
                ('issuing_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.issuingagency')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='responsible_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.localauthority'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(max_length=255)),
                ('subdistrict', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('province', models.CharField(default='ภูเก็ต', max_length=120)),
                ('postal_code', models.CharField(max_length=10)),
                ('rooms', models.PositiveIntegerField()),
                ('max_guests', models.PositiveIntegerField()),
                ('has_restaurant', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.localauthority')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.propertytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.property'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('fee_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_currency_snapshot', models.CharField(max_length=3)),
                ('validity_years_snapshot', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='license', to='core.application')),
                ('fee_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='core.feeschedule')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='core.propertytype')),
            ],
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='core.propertytype'),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='result_property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classification_rules', to='core.propertytype'),
        ),
        migrations.AddField(
            model_name='application',
            name='confirmed_property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.propertytype'),
        ),
        migrations.CreateModel(
            name='PropertyTypeDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_requirements', to='core.documenttype')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_requirements', to='core.propertytype')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SUBMIT', 'Ready to submit'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REVISION_REQUIRED', 'Revision required'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SUBMIT', 'Ready to submit'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REVISION_REQUIRED', 'Revision required'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='core.application')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='status_app_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id', '-created_at'], name='audit_object_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='core.application')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_requirements', to='core.documenttype')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('application', 'document_type'), name='uniq_application_document_req')],
            },
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application', 'document_type', 'is_current'], name='document_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(fields=('application', 'document_type', 'version'), name='uniq_document_version'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application', 'document_type'), name='uniq_current_document'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='document_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='document_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='documenttypetranslation',
            constraint=models.UniqueConstraint(fields=('document_type', 'language_code'), name='uniq_document_type_lang'),
        ),
        migrations.AddConstraint(
            model_name='issuingagencytranslation',
            constraint=models.UniqueConstraint(fields=('issuing_agency', 'language_code'), name='uniq_agency_lang'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'local_authority'], name='user_role_authority_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_user_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('local_authority__isnull', False), ('role', 'LOCAL_OFFICER')), models.Q(('role', 'LOCAL_OFFICER'), _negated=True), _connector='OR'), name='local_officer_has_authority'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'LOCAL_OFFICER'), ('local_authority__isnull', True), _connector='OR'), name='only_local_officer_authority'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount_snapshot__gte', 0)), name='license_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('validity_years_snapshot__gt', 0)), name='license_validity_positive'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('validity_years__gt', 0)), name='fee_validity_positive'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='fee_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.UniqueConstraint(fields=('property_type', 'currency', 'effective_from'), name='uniq_fee_effective_start'),
        ),
        migrations.AddConstraint(
            model_name='classificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('priority',), name='uniq_active_rule_priority'),
        ),
        migrations.AddConstraint(
            model_name='classificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_rooms__isnull', True), ('max_rooms__isnull', True), ('min_rooms__lte', models.F('max_rooms')), _connector='OR'), name='rule_valid_room_bounds'),
        ),
        migrations.AddConstraint(
            model_name='classificationrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_guests__isnull', True), ('max_guests__isnull', True), ('min_guests__lte', models.F('max_guests')), _connector='OR'), name='rule_valid_guest_bounds'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['property', 'status'], name='app_property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['responsible_authority', 'status'], name='app_authority_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertytypedocumentrequirement',
            constraint=models.UniqueConstraint(fields=('property_type', 'document_type'), name='uniq_type_document_req'),
        ),
        migrations.AddConstraint(
            model_name='propertytypetranslation',
            constraint=models.UniqueConstraint(fields=('property_type', 'language_code'), name='uniq_property_type_lang'),
        ),
    ]
