# Generated by Django 5.2.17 on 2026-09-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'SUPER_ADMIN'), _negated=True), ('is_staff', True), _connector='OR'), name='super_admin_is_staff'),
        ),
    ]
