# Generated by Django 5.2.17 on 2026-09-19 06:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_super_admin_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'ordering': ['document_type_id', '-version', 'attachment_index']},
        ),
        migrations.RemoveConstraint(
            model_name='applicationdocument',
            name='uniq_document_version',
        ),
        migrations.RemoveConstraint(
            model_name='applicationdocument',
            name='uniq_current_document',
        ),
        migrations.RemoveConstraint(
            model_name='license',
            name='license_fee_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='license',
            name='license_validity_positive',
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='attachment_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='applicationrequirement',
            name='step_code',
            field=models.CharField(choices=[('APPLICANT', 'Applicant and business'), ('PREMISES', 'Premises and legal right'), ('FACILITIES', 'Rooms and facilities'), ('SAFETY', 'Safety and compliance'), ('MANAGER', 'Accommodation manager')], default='APPLICANT', max_length=30),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='allows_multiple_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='artifact_kind',
            field=models.CharField(choices=[('HOTEL_LICENSE', 'Hotel license'), ('NOTIFICATION_ACKNOWLEDGEMENT', 'Notification acknowledgement')], default='HOTEL_LICENSE', max_length=40),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='issues_license',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertytypedocumentrequirement',
            name='step_code',
            field=models.CharField(choices=[('APPLICANT', 'Applicant and business'), ('PREMISES', 'Premises and legal right'), ('FACILITIES', 'Rooms and facilities'), ('SAFETY', 'Safety and compliance'), ('MANAGER', 'Accommodation manager')], default='APPLICANT', max_length=30),
        ),
        migrations.AlterField(
            model_name='license',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='fee_amount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='license',
            name='fee_currency_snapshot',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='license',
            name='fee_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='core.feeschedule'),
        ),
        migrations.AlterField(
            model_name='license',
            name='validity_years_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(fields=('application', 'document_type', 'version', 'attachment_index'), name='uniq_document_attachment_version'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application', 'document_type', 'attachment_index'), name='uniq_current_document_attachment'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.CheckConstraint(condition=models.Q(('attachment_index__gt', 0)), name='document_attachment_index_positive'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount_snapshot__isnull', True), ('fee_amount_snapshot__gte', 0), _connector='OR'), name='license_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('validity_years_snapshot__isnull', True), ('validity_years_snapshot__gt', 0), _connector='OR'), name='license_validity_positive'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artifact_kind', 'HOTEL_LICENSE'), ('expires_at__isnull', False), ('fee_amount_snapshot__isnull', False), ('fee_schedule__isnull', False), ('validity_years_snapshot__isnull', False)), models.Q(('artifact_kind', 'NOTIFICATION_ACKNOWLEDGEMENT'), ('expires_at__isnull', True), ('fee_amount_snapshot__isnull', True), ('fee_currency_snapshot', ''), ('fee_schedule__isnull', True), ('validity_years_snapshot__isnull', True)), _connector='OR'), name='license_artifact_fields_match_kind'),
        ),
    ]
