# Generated by Django 5.2.17 on 2026-09-19 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_caselibraryarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralAssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_code', models.CharField(choices=[('CLASSIFICATION_AMBIGUITY', 'Classification ambiguity'), ('REQUIREMENT_APPLICABILITY', 'Document requirement applicability'), ('WORKFLOW_EXCEPTION', 'Workflow exception'), ('POLICY_INTERPRETATION', 'Policy interpretation')], max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('property_type_code_snapshot', models.CharField(blank=True, max_length=40)),
                ('classification_outcome_snapshot', models.CharField(max_length=50)),
                ('rooms_snapshot', models.PositiveIntegerField()),
                ('max_guests_snapshot', models.PositiveIntegerField()),
                ('restaurant_snapshot', models.BooleanField()),
                ('application_status_snapshot', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SUBMIT', 'Ready to submit'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REVISION_REQUIRED', 'Revision required'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30)),
                ('required_documents_snapshot', models.PositiveIntegerField()),
                ('approved_documents_snapshot', models.PositiveIntegerField()),
                ('resolution_code', models.CharField(blank=True, choices=[('FOLLOW_CURRENT_RULES', 'Follow the current rules'), ('REQUEST_MORE_EVIDENCE', 'Request more evidence'), ('ESCALATE_OFFLINE', 'Escalate through the official offline channel'), ('NO_CENTRAL_DECISION', 'Central office cannot decide from this snapshot')], max_length=40)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='central_assistance_requests', to='core.application')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='central_assistance_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_central_assistance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='central_help_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('application',), name='uniq_open_central_assistance_per_app'), models.CheckConstraint(condition=models.Q(models.Q(('resolution_code', ''), ('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status', 'OPEN')), models.Q(('resolution_code__gt', ''), ('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status', 'RESOLVED')), _connector='OR'), name='central_assistance_resolution_state')],
            },
        ),
    ]
