# Generated by Django 5.2.17 on 2026-09-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_discussionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('services', models.JSONField(default=list)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('price_note_th', models.CharField(blank=True, max_length=255)),
                ('price_note_en', models.CharField(blank=True, max_length=255)),
                ('contact_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_status', models.CharField(choices=[('DEMO_ONLY', 'Fictional demo entry'), ('SELF_DECLARED', 'Provider self-declared'), ('PUBLIC_SOURCE', 'Published public source')], max_length=20)),
                ('source_checked_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='provider_active_name_idx')],
            },
        ),
    ]
